terraform {
  required_providers {
    nullplatform = {
      source = "nullplatform/nullplatform"
    }
  }
}

provider "nullplatform" {}

variable "application_id" {
  description = "ID of the nullplatform application the dimension is scoped to."
  type        = number
}

# Resolve the application NRN instead of hardcoding it.
data "nullplatform_application" "app" {
  id = var.application_id
}

# A dimension is an axis (e.g. Environment, Region) used to scope
# configuration, parameters and provider configs across the platform.
resource "nullplatform_dimension" "environment" {
  nrn   = data.nullplatform_application.app.nrn
  name  = "Environment"
  order = 1 # order in which dimensions are evaluated/displayed
}

output "dimension_slug" {
  description = "Slug generated by the platform for the dimension."
  value       = nullplatform_dimension.environment.slug
}
